### ISSUE TITLE
KeyError / AssertionError

### ISSUE THREAD

**Issue by crsabbagh** [usenocturne/nocturne-image#8]
Whenever I try running `python superbird_tool.py --dont_reset --restore_device C:\path\to\nocturne-image\image`, I get the following errors.  I have tried using multiple different USB cables, different ports, and 3 different computers (my main computer has an AMD processor, which I know has some issues running superbird, so I tried a laptop with an Intel chip and it still didn't work).  The script will run, disconnect my carthing and then reconnect it (I hear the Windows alert sounds) and then throw the error below.

```
Spotify Car Thing (superbird) toolkit, v0.1.9, by Thing Labs and Bishop Dynamics
     https://github.com/thinglabsoss/superbird-tool
     Forked from https://github.com/bishopdynamics/superbird-tool

Found device booted in USB Mode (buttons 1 & 4 held at boot)
Entering USB Burn Mode
writing images/superbird.bl2.encrypted.bin at 0xfffa0000
 writing to: 0xfffa0000
Traceback (most recent call last):
  File "C:\Users\crsab\Downloads\Nocturne\superbird-tool-main\superbird_tool.py", line 334, in <module>
    dev = enter_burn_mode(dev)
  File "C:\Users\crsab\Downloads\Nocturne\superbird-tool-main\superbird_device.py", line 124, in enter_burn_mode
    dev.bl2_boot('images/superbird.bl2.encrypted.bin', 'images/superbird.bootloader.img')
  File "C:\Users\crsab\Downloads\Nocturne\superbird-tool-main\superbird_device.py", line 288, in bl2_boot
    self.send_file(bl2_file, self.ADDR_BL2, chunk_size=4096, append_zeros=True)
  File "C:\Users\crsab\Downloads\Nocturne\superbird-tool-main\superbird_device.py", line 283, in send_file
    self.write(address, file_data, chunk_size, append_zeros)
  File "C:\Users\crsab\Downloads\Nocturne\superbird-tool-main\superbird_device.py", line 259, in write
    self.device.writeLargeMemory(address, data, chunk_size, append_zeros)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\pyamlboot\pyamlboot.py", line 255, in writeLargeMemory
    self._writeLargeMemory(address+offset, data[offset:offset+writeLength], \
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\pyamlboot\pyamlboot.py", line 236, in _writeLargeMemory
    ep.write(data[offset:offset+blockLength], 1000)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 408, in write
    return self.device.write(self, data, timeout)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 986, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 229, in setup_request
    self.managed_claim_interface(device, intf)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 178, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\backend\libusb0.py", line 537, in claim_interface
    _check(_lib.usb_claim_interface(dev_handle, intf))
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\backend\libusb0.py", line 447, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [claim_interface] could not claim interface 0, invalid configuration 0\n'

C:\Users\crsab\Downloads\Nocturne\superbird-tool-main>python superbird_tool.py --dont_reset --restore_device C:\Users\crsab\Downloads\Nocturne\superbird-tool-main\images
Spotify Car Thing (superbird) toolkit, v0.1.9, by Thing Labs and Bishop Dynamics
     https://github.com/thinglabsoss/superbird-tool
     Forked from https://github.com/bishopdynamics/superbird-tool

Found device booted in USB Mode (buttons 1 & 4 held at boot)
Entering USB Burn Mode
writing images/superbird.bl2.encrypted.bin at 0xfffa0000
 writing to: 0xfffa0000
AMLC dataSize=16384, offset=65536, seq=0
[DONE]
AMLC dataSize=49152, offset=393216, seq=1
[DONE]
AMLC dataSize=16384, offset=229376, seq=2
[DONE]
AMLC dataSize=49152, offset=180224, seq=3
[DONE]
AMLC dataSize=16384, offset=65536, seq=4
[DONE]
AMLC dataSize=1224048, offset=81920, seq=5
[DONE]
[BL2 END]
Waiting for device...
Make sure you've installed the correct driver using Zadig.
Make sure you've installed the correct driver using Zadig.
Device is now in USB Burn Mode
 executing bulkcmd: "amlmmc part 1"
Traceback (most recent call last):
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 236, in get_interface_and_endpoint
    return self._ep_info[endpoint_address]
KeyError: 129

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\crsab\Downloads\Nocturne\superbird-tool-main\superbird_tool.py", line 334, in <module>
    dev = enter_burn_mode(dev)
  File "C:\Users\crsab\Downloads\Nocturne\superbird-tool-main\superbird_device.py", line 138, in enter_burn_mode
    dev.bulkcmd('amlmmc part 1')
  File "C:\Users\crsab\Downloads\Nocturne\superbird-tool-main\superbird_device.py", line 223, in bulkcmd
    resp = self.device.bulkCmd(command)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\pyamlboot\pyamlboot.py", line 590, in bulkCmd
    return self.bulkCmdStat(timeout)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\pyamlboot\pyamlboot.py", line 595, in bulkCmdStat
    return self.dev.read(usb.util.ENDPOINT_IN | 1, BULK_REPLY_LEN,
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 1021, in read
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 228, in setup_request
    intf, ep = self.get_interface_and_endpoint(device, endpoint_address)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 238, in get_interface_and_endpoint
    for intf in self.get_active_configuration(device):
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\core.py", line 252, in get_active_configuration
    bConfigurationValue=self.backend.get_configuration(self.handle)
  File "C:\Users\crsab\AppData\Local\Programs\Python\Python310\lib\site-packages\usb\backend\libusb0.py", line 528, in get_configuration
    assert ret == 1
AssertionError
```

**Comment by crsabbagh** [comment]
Some additional context:

- I previously successfully installed DeskThing on my carthing using their installer (not superbird)
- I followed the Nocturne youtube tutorial from the very beginning and everything was successful until trying to flash Nocturne using the superbird tool

**Comment by itsnebulalol** [comment]
Please follow the [troubleshooting steps](https://github.com/usenocturne/nocturne-image?tab=readme-ov-file#troubleshooting) for your issue, then report back.

**Comment by crsabbagh** [comment]
Doh, that fixed it.  Sorry about that!  But now I'm unfortunately running into another issue with RealVNC.  I'm getting a "Timed out waiting for a response from the computer" error.  The carthing is showing a "No Internet" page with a "DNS_PROBE_FINISHED_NO_INTERNET" error, if that's relevant.  Let me know if you want me to start a new thread for this issue.  Thanks!

**Comment by itsnebulalol** [comment]
Are you using Raspberry Pi OS Legacy? That is required for networking to work properly as of now.

**Comment by crsabbagh** [comment]
That was the problem--I installed the legacy OS, and everything worked correctly.  Thank you!
